GXX= g++
# CPP_FILE = NimGameII.cpp
# IN_FILE = inputs/NimGameII.in
CPP_FILE = JosephusQueries.cpp
IN_FILE = inputs/JosephusQueries.in
OUT_FILE = a.out

compile:
	$(GXX) $(CPP_FILE) -o $(OUT_FILE) -Wall -Werror
	./$(OUT_FILE) < $(IN_FILE)

